/*
 * File: app/view/navigation/Panel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Qtm.view.navigation.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navigationpanel',

    requires: [
        'Qtm.view.navigation.PanelViewModel',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'navigationpanel'
    },
    itemId: 'navigator',
    width: 250,
    layout: 'accordion',
    collapseDirection: 'left',
    frameHeader: false,
    header: false,
    title: 'Menu',

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            glyph: 'xf002@fontawesome',
            title: 'NAS',
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    itemId: 'menu',
                    plain: true,
                    items: [
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'Group 3',
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    itemId: 'menu3',
                    items: [
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                }
            ]
        }
    ]

});